### ISSUE TITLE
[ docker-compose.yml ] CHANGEME comments

### ISSUE THREAD

**Issue by cig0** [paralect/deploy-drone#3]
Hi,

I believe that the CHANGEME reminders were intended for the variables that later have been moved to the drone.env file, right?

Thanks

**Comment by anorsich** [comment]
Thank you, @cig0. You are correct CHANGEME comments were a part of original Drone template. I just removed these comments and also created a separate issue (#4 ) to track local drone configuration fixes and updates. If you already tested local configuration on most recent versions of Drone we'd be happy to review your PR :) Feel free to close this issue if you think your question was answered.

**Comment by cig0** [comment]
Hi Andrew, I tested your configuration agains Drone 0.8.4 and works well, no need to change anything.

**Comment by anorsich** [comment]
@cig0 Thank you for letting us know, I'll update the issue and remove my comment!
